// Command wire-codegen generates TypeScript constants from Go wire types.
// Output: static-src/wire/constants.gen.ts
//
// Run: go run ./cmd/wire-codegen   (from apps/vibecli/)
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WireConst defines a wire protocol constant to emit into constants.gen.ts.
type WireConst struct {
	TSName string
	Value  int
}

// WireConstants is the single source of truth for wire message type tags and
// mode flags shared between Go (wire_binary.go) and TypeScript (wire-binary.ts).
var WireConstants = []WireConst{
	{"MSG_SCREEN", 0},
	{"MSG_SCROLL", 1},
	{"MSG_RESUME_ACK", 2},
	{"MSG_MODES", 3},
	{"MODE_FLAG_BRACKETED_PASTE", 0x01},
	{"MODE_FLAG_APP_CURSOR_KEYS", 0x02},
}

// generateConstants writes constants.gen.ts.
func generateConstants(w *strings.Builder) {
	w.WriteString("// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.\n\n")
	for _, c := range WireConstants {
		fmt.Fprintf(w, "export const %s = %d;\n", c.TSName, c.Value)
	}
}

func main() {
	outDir := filepath.Join("static-src", "wire")
	if err := os.MkdirAll(outDir, 0o755); err != nil { // #nosec G301 -- generated source directory
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", outDir, err)
		os.Exit(1)
	}

	var constantsBuf strings.Builder
	generateConstants(&constantsBuf)
	if err := os.WriteFile(filepath.Join(outDir, "constants.gen.ts"), []byte(constantsBuf.String()), 0o644); err != nil { // #nosec G306 -- generated source
		fmt.Fprintf(os.Stderr, "write constants.gen.ts: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("wire-codegen: generated static-src/wire/constants.gen.ts")
}
