// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export const MSG_SCREEN = 0;
export const MSG_SCROLL = 1;
export const MSG_RESUME_ACK = 2;
export const MSG_MODES = 3;
export const MODE_FLAG_BRACKETED_PASTE = 1;
export const MODE_FLAG_APP_CURSOR_KEYS = 2;
