// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { asObject, reqStr, optStr, type Decoder } from "../validators.js";
import type { APIError, LoginScanResult, LogoutResponse, WhoamiErrorResponse } from "./types.gen.js";

export const decodeAPIError: Decoder<APIError> = (v) => {
  const o = asObject(v, "$.api_error");
  const out: APIError = {
    error: reqStr(o, "error", "$.api_error"),
  };
  const code = optStr(o, "code", "$.api_error");
  if (code !== undefined) out.code = code;
  const requestId = optStr(o, "request_id", "$.api_error");
  if (requestId !== undefined) out.request_id = requestId;
  return out;
};

export const decodeLoginScanResult: Decoder<LoginScanResult> = (v) => {
  const o = asObject(v, "$.login_scan_result");
  const out: LoginScanResult = {
  };
  const url = optStr(o, "url", "$.login_scan_result");
  if (url !== undefined) out.url = url;
  const code = optStr(o, "code", "$.login_scan_result");
  if (code !== undefined) out.code = code;
  const error = optStr(o, "error", "$.login_scan_result");
  if (error !== undefined) out.error = error;
  return out;
};

export const decodeLogoutResponse: Decoder<LogoutResponse> = (v) => {
  const o = asObject(v, "$.logout_response");
  const out: LogoutResponse = {
    output: reqStr(o, "output", "$.logout_response"),
  };
  const error = optStr(o, "error", "$.logout_response");
  if (error !== undefined) out.error = error;
  return out;
};

export const decodeWhoamiErrorResponse: Decoder<WhoamiErrorResponse> = (v) => {
  const o = asObject(v, "$.whoami_error_response");
  const out: WhoamiErrorResponse = {
    error: reqStr(o, "error", "$.whoami_error_response"),
  };
  return out;
};

