// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export interface APIError {
  error: string;
  code?: string;
  request_id?: string;
}

export interface LoginScanResult {
  url?: string;
  code?: string;
  error?: string;
}

export interface LogoutResponse {
  output: string;
  error?: string;
}

export interface WhoamiErrorResponse {
  error: string;
}

