#!/usr/bin/env bash
# Deploy the locally-built web-terminal-kiro-dev-bin into the web-terminal-kiro-dev
# container on the dev box (the rebuild experiment target, host port 9849) by
# swapping the binary and restarting — no image rebuild, no GitHub Actions. Pairs
# with scripts/dev-build.sh. Leaves prod web-terminal-kiro (9848) untouched.
#
# Set DEPLOY_HOST to your dev box (an ssh host alias or IP).
set -euo pipefail
cd "$(dirname "$0")/.."
HOST="${DEPLOY_HOST:?set DEPLOY_HOST to your dev box (ssh host or IP)}"
# Per-operation wall-clock deadline for every ssh/scp invocation below. The
# SSH transport options (SSH_OPTS) only prove the transport is alive: a wedged
# remote command (e.g. a hung Docker daemon) keeps answering keepalives while
# never returning, so each remote operation also runs under a local `timeout`
# cap. Health-loop inspect samples use a shorter fixed cap (see the poll loop)
# so one stuck sample cannot overrun the DEPLOY_TIMEOUT budget.
REMOTE_OP_TIMEOUT="${REMOTE_OP_TIMEOUT:-120}"
if [[ ! "$REMOTE_OP_TIMEOUT" =~ ^[0-9]{1,9}$ ]]; then
  printf 'error: REMOTE_OP_TIMEOUT must be a non-negative decimal integer (at most 9 digits), got %q\n' "$REMOTE_OP_TIMEOUT" >&2
  exit 1
fi
# DEPLOY_HOST may be an ssh config alias (documented above), which curl/DNS
# cannot resolve. ssh -G prints the effective HostName for an alias and
# echoes a bare IP/hostname unchanged, so this is a no-op for direct values.
# ssh -G is nominally local, but a Match exec directive in ssh config runs an
# arbitrary external command, so it gets the same wall-clock cap.
PROBE_HOST=$(timeout --signal=TERM --kill-after=5s "${REMOTE_OP_TIMEOUT}s" ssh -G "$HOST" | awk '/^hostname /{print $2; exit}')
: "${PROBE_HOST:?failed to resolve DEPLOY_HOST via ssh -G}"
# Bound every ssh/scp invocation the same way the health curl is bounded
# (-m5), at both stages: ConnectTimeout caps connection setup (without it a
# dev box that stops answering TCP mid-poll blocks a single ssh on the
# kernel's SYN retry schedule), and ServerAliveInterval/CountMax fail an
# established transport that goes silent after ~30s — ConnectTimeout does
# not detect a session that dies post-handshake, so a remote mktemp/docker/
# poll command could otherwise hang past the DEPLOY_TIMEOUT budget. Both
# leave responsive long-running commands unchanged. (No BatchMode=yes —
# that would change behavior for password-auth dev boxes.)
SSH_OPTS=(-o ConnectTimeout=10 -o ServerAliveInterval=10 -o ServerAliveCountMax=3)
BIN="web-terminal-kiro-dev-bin"
[ -f "$BIN" ] || {
  printf 'missing %s — run scripts/dev-build.sh first\n' "$BIN" >&2
  exit 1
}

# Stage into a remote mktemp path owned by the ssh user (mode 0600, random
# suffix) so no other local user on the dev box can pre-create or swap the
# binary between scp and docker cp.
REMOTE_TMP=$(timeout --signal=TERM --kill-after=5s "${REMOTE_OP_TIMEOUT}s" ssh "${SSH_OPTS[@]}" "$HOST" "mktemp /tmp/web-terminal-kiro-dev-bin.XXXXXX")
echo "scp -> ${HOST}:${REMOTE_TMP}"
if ! timeout --signal=TERM --kill-after=5s "${REMOTE_OP_TIMEOUT}s" scp "${SSH_OPTS[@]}" -q "$BIN" "${HOST}:${REMOTE_TMP}"; then
  # REMOTE_TMP came from remote mktemp and is intentionally expanded locally.
  # shellcheck disable=SC2029
  timeout --signal=TERM --kill-after=5s "${REMOTE_OP_TIMEOUT}s" ssh "${SSH_OPTS[@]}" "$HOST" "rm -f ${REMOTE_TMP}" >/dev/null 2>&1 || true
  exit 1
fi
echo "docker cp + restart web-terminal-kiro-dev"
# REMOTE_TMP is generated by mktemp above (not user input); expanding it
# client-side into the remote command is intentional — SC2029's
# client-vs-server caveat is moot here.
# Stage to a distinct in-container path, set the executable mode explicitly
# (the mktemp staging file is 0600 and docker cp preserves metadata), then
# atomically rename over the live binary so a failed copy never leaves a
# partial or non-executable /app/web-terminal-kiro behind.
# The composite cp/exec/restart chain runs under the same single wall-clock
# cap: a wedged Docker daemon answers SSH keepalives forever while never
# returning, which is exactly the hang the transport options cannot catch.
# shellcheck disable=SC2029
timeout --signal=TERM --kill-after=5s "${REMOTE_OP_TIMEOUT}s" ssh "${SSH_OPTS[@]}" "$HOST" "trap 'rm -f ${REMOTE_TMP}' EXIT; sudo docker cp ${REMOTE_TMP} web-terminal-kiro-dev:/app/web-terminal-kiro.new && sudo docker exec web-terminal-kiro-dev sh -c 'chmod 0755 /app/web-terminal-kiro.new && mv -f /app/web-terminal-kiro.new /app/web-terminal-kiro' && sudo docker restart web-terminal-kiro-dev"
# Bounded health poll. The entrypoint's foreground work before the server
# binds can legally take up to ~1080s on a cold volume (kiro-cli download +
# install + probes + optional APT_PACKAGES), so a single early probe would
# fail a normally progressing boot. DEPLOY_TIMEOUT defaults to the same
# derived budget as the image HEALTHCHECK start-period (20m) and
# tests/image-smoke.conf SMOKE_TIMEOUT — keep the three in lockstep. The
# poll succeeds on HTTP 200, fails immediately if the container exits OR is
# restarted by the restart policy (under `restart: unless-stopped` a crashing
# entrypoint is relaunched between 5s samples, so .State.Running alone can
# read true on every sample; a growing .RestartCount is the reliable exit
# signal), and otherwise waits through transient starting/unhealthy states.
DEPLOY_TIMEOUT="${DEPLOY_TIMEOUT:-1260}"
if [[ ! "$DEPLOY_TIMEOUT" =~ ^[0-9]{1,9}$ ]]; then
  printf 'error: DEPLOY_TIMEOUT must be a non-negative decimal integer (at most 9 digits), got %q\n' "$DEPLOY_TIMEOUT" >&2
  exit 1
fi
echo "waiting for web-terminal-kiro-dev health (timeout ${DEPLOY_TIMEOUT}s)"
# Baseline the restart count right after the explicit docker restart: any
# later increase means the entrypoint died and the restart policy relaunched it.
# The baseline is mandatory — synthesizing it from a later sample would adopt a
# post-crash count as normal and blind the restart-growth crash detector.
if ! base_restarts=$(timeout --signal=TERM --kill-after=5s "${REMOTE_OP_TIMEOUT}s" ssh "${SSH_OPTS[@]}" "$HOST" "sudo docker inspect -f '{{.RestartCount}}' web-terminal-kiro-dev" 2>/dev/null); then
  printf 'deploy verification failed: could not establish restart-count baseline\n' >&2
  exit 1
fi
case "$base_restarts" in
  '' | *[!0-9]*)
    printf 'deploy verification failed: invalid restart-count baseline: %s\n' "$base_restarts" >&2
    exit 1
    ;;
esac
deadline=$(($(date +%s) + 10#$DEPLOY_TIMEOUT))
code="ERR"
while [ "$(date +%s)" -lt "$deadline" ]; do
  # Shorter fixed 15s cap here (not REMOTE_OP_TIMEOUT): a single stuck inspect
  # sample must not overrun the DEPLOY_TIMEOUT budget; a timed-out sample
  # falls into the existing "unknown unknown" skip path below.
  state=$(timeout --signal=TERM --kill-after=5s 15s ssh "${SSH_OPTS[@]}" "$HOST" "sudo docker inspect -f '{{.State.Running}} {{.RestartCount}}' web-terminal-kiro-dev" 2>/dev/null || echo "unknown unknown")
  running=${state%% *}
  restarts=${state##* }
  if [ "$running" = "false" ]; then
    printf 'deploy verification failed: container exited during startup\n' >&2
    exit 1
  fi
  case "$restarts" in
    # An inspect failed this sample; skip it. The baseline is always numeric
    # (established mandatorily above), so a blip never disables the detector.
    '' | *[!0-9]*) : ;;
    *)
      if [ "$restarts" -gt "$base_restarts" ]; then
        printf 'deploy verification failed: container restarted during startup (restart count %s -> %s)\n' "$base_restarts" "$restarts" >&2
        exit 1
      fi
      ;;
  esac
  code=$(curl -sf -m5 -o /dev/null -w "%{http_code}" "http://${PROBE_HOST}:9849/api/health") || true
  case "$code" in '' | 000) code="ERR" ;; esac
  [ "$code" = "200" ] && break
  sleep 5
done
echo "web-terminal-kiro-dev health: $code  (UI: http://${PROBE_HOST}:9849/)"
[ "$code" = "200" ] || {
  printf 'deploy verification failed (health=%s after %ss)\n' "$code" "$DEPLOY_TIMEOUT" >&2
  exit 1
}
