#!/usr/bin/env bash
# Deploy the locally-built web-terminal-kiro-dev-bin into the web-terminal-kiro-dev
# container on the dev box (the rebuild experiment target, host port 9849) by
# swapping the binary and restarting — no image rebuild, no GitHub Actions. Pairs
# with scripts/dev-build.sh. Leaves prod web-terminal-kiro (9848) untouched.
#
# Set DEPLOY_HOST to your dev box (an ssh host alias or IP).
set -euo pipefail
cd "$(dirname "$0")/.."
HOST="${DEPLOY_HOST:?set DEPLOY_HOST to your dev box (ssh host or IP)}"
BIN="web-terminal-kiro-dev-bin"
[ -f "$BIN" ] || {
  echo "missing $BIN — run scripts/dev-build.sh first" >&2
  exit 1
}

# Stage into a remote mktemp path owned by the ssh user (mode 0600, random
# suffix) so no other local user on the dev box can pre-create or swap the
# binary between scp and docker cp.
REMOTE_TMP=$(ssh "$HOST" "mktemp /tmp/web-terminal-kiro-dev-bin.XXXXXX")
echo "scp -> ${HOST}:${REMOTE_TMP}"
if ! scp -q "$BIN" "${HOST}:${REMOTE_TMP}"; then
  # REMOTE_TMP came from remote mktemp and is intentionally expanded locally.
  # shellcheck disable=SC2029
  ssh "$HOST" "rm -f ${REMOTE_TMP}" >/dev/null 2>&1 || true
  exit 1
fi
echo "docker cp + restart web-terminal-kiro-dev"
# REMOTE_TMP is generated by mktemp above (not user input); expanding it
# client-side into the remote command is intentional — SC2029's
# client-vs-server caveat is moot here.
# shellcheck disable=SC2029
ssh "$HOST" "trap 'rm -f ${REMOTE_TMP}' EXIT; sudo docker cp ${REMOTE_TMP} web-terminal-kiro-dev:/app/web-terminal-kiro && sudo docker restart web-terminal-kiro-dev"
sleep 6
code=$(curl -sf -m5 -o /dev/null -w "%{http_code}" "http://${HOST}:9849/api/health" || echo "ERR")
echo "web-terminal-kiro-dev health: $code  (UI: http://${HOST}:9849/)"
[ "$code" = "200" ] || {
  echo "deploy verification failed (health=$code)" >&2
  exit 1
}
