#!/usr/bin/env bash
# Deploy the locally-built web-terminal-kiro-dev-bin into the web-terminal-kiro-dev
# container on the dev box (the rebuild experiment target, host port 9849) by
# swapping the binary and restarting — no image rebuild, no GitHub Actions. Pairs
# with scripts/dev-build.sh. Leaves prod web-terminal-kiro (9848) untouched.
#
# Set DEPLOY_HOST to your dev box (an ssh host alias or IP).
set -euo pipefail
cd "$(dirname "$0")/.."
HOST="${DEPLOY_HOST:?set DEPLOY_HOST to your dev box (ssh host or IP)}"
BIN="web-terminal-kiro-dev-bin"
[ -f "$BIN" ] || {
  echo "missing $BIN — run scripts/dev-build.sh first" >&2
  exit 1
}

# Stage into a remote mktemp path owned by the ssh user (mode 0600, random
# suffix) so no other local user on the dev box can pre-create or swap the
# binary between scp and docker cp.
REMOTE_TMP=$(ssh "$HOST" "mktemp /tmp/web-terminal-kiro-dev-bin.XXXXXX")
echo "scp -> ${HOST}:${REMOTE_TMP}"
if ! scp -q "$BIN" "${HOST}:${REMOTE_TMP}"; then
  # REMOTE_TMP came from remote mktemp and is intentionally expanded locally.
  # shellcheck disable=SC2029
  ssh "$HOST" "rm -f ${REMOTE_TMP}" >/dev/null 2>&1 || true
  exit 1
fi
echo "docker cp + restart web-terminal-kiro-dev"
# REMOTE_TMP is generated by mktemp above (not user input); expanding it
# client-side into the remote command is intentional — SC2029's
# client-vs-server caveat is moot here.
# Stage to a distinct in-container path, set the executable mode explicitly
# (the mktemp staging file is 0600 and docker cp preserves metadata), then
# atomically rename over the live binary so a failed copy never leaves a
# partial or non-executable /app/web-terminal-kiro behind.
# shellcheck disable=SC2029
ssh "$HOST" "trap 'rm -f ${REMOTE_TMP}' EXIT; sudo docker cp ${REMOTE_TMP} web-terminal-kiro-dev:/app/web-terminal-kiro.new && sudo docker exec web-terminal-kiro-dev sh -c 'chmod 0755 /app/web-terminal-kiro.new && mv -f /app/web-terminal-kiro.new /app/web-terminal-kiro' && sudo docker restart web-terminal-kiro-dev"
# Bounded health poll. The entrypoint's foreground work before the server
# binds can legally take up to ~1080s on a cold volume (kiro-cli download +
# install + probes + optional APT_PACKAGES), so a single early probe would
# fail a normally progressing boot. DEPLOY_TIMEOUT defaults to the same
# derived budget as the image HEALTHCHECK start-period (20m) and
# tests/image-smoke.conf SMOKE_TIMEOUT — keep the three in lockstep. The
# poll succeeds on HTTP 200, fails immediately if the container exits, and
# otherwise waits through transient starting/unhealthy states.
DEPLOY_TIMEOUT="${DEPLOY_TIMEOUT:-1260}"
echo "waiting for web-terminal-kiro-dev health (timeout ${DEPLOY_TIMEOUT}s)"
deadline=$(($(date +%s) + DEPLOY_TIMEOUT))
code="ERR"
while [ "$(date +%s)" -lt "$deadline" ]; do
  running=$(ssh "$HOST" "sudo docker inspect -f '{{.State.Running}}' web-terminal-kiro-dev" 2>/dev/null || echo "unknown")
  if [ "$running" = "false" ]; then
    echo "deploy verification failed: container exited during startup" >&2
    exit 1
  fi
  code=$(curl -sf -m5 -o /dev/null -w "%{http_code}" "http://${HOST}:9849/api/health" || echo "ERR")
  [ "$code" = "200" ] && break
  sleep 5
done
echo "web-terminal-kiro-dev health: $code  (UI: http://${HOST}:9849/)"
[ "$code" = "200" ] || {
  echo "deploy verification failed (health=$code after ${DEPLOY_TIMEOUT}s)" >&2
  exit 1
}
