name: Build and Push

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "go.mod"
      - "*.go"
      - "internal/**"
      - "static-src/**"
      - "entrypoint.sh"
      - "setup-tools.sh"
      - "tools.json"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  release:
    uses: cplieger/ci/.github/workflows/docker-release.yaml@a4a5c8d560e69958c08f1294f699a9c41d187a23 # v1
    with:
      registries: "ghcr"
      sbom-from: "path"
      notify-repo: "cplieger/homelab"
    secrets: inherit
