name: Build and Push

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "go.mod"
      - "*.go"
      - "internal/**"
      - "static-src/**"
      - "entrypoint.sh"
      - "setup-tools.sh"
      - "tools.json"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  release:
    uses: cplieger/ci/.github/workflows/docker-release.yaml@bd60d228e855bfe73901919383b8750790fbbece # v1
    with:
      registries: "ghcr"
      sbom-from: "path"
      notify-repo: "cplieger/homelab"
    secrets: inherit
