name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go:
    uses: cplieger/ci/.github/workflows/go-ci.yaml@17b699a97542f07b55e6b576456044731954c6fd # v1
    with:
      working-directory: "."
      go-version-file: "go.mod"
  web:
    uses: cplieger/ci/.github/workflows/ts-ci.yaml@17b699a97542f07b55e6b576456044731954c6fd # v1
    with:
      working-directory: "static-src"
      web-lint: true