name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  go:
    uses: cplieger/ci/.github/workflows/go-ci.yaml@bd60d228e855bfe73901919383b8750790fbbece # v1
    with:
      app: true
      dockerfile-lint: true
      working-directory: "."
      go-version-file: "go.mod"

  web:
    uses: cplieger/ci/.github/workflows/ts-ci.yaml@bd60d228e855bfe73901919383b8750790fbbece # v1
    with:
      working-directory: "static-src"
      web-lint: true
