name: Security

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - Dockerfile
      - .github/workflows/security.yml
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    uses: cplieger/ci/.github/workflows/security-scan.yaml@9b2898bfe97027eb3986d61276b82b390f7529b8 # v2
