name: Security

on:
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".github/workflows/security.yml"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    uses: cplieger/ci/.github/workflows/security-scan.yaml@98c2f685fa19abbbc43735b1108bfd53d30e65e0 # v1
